version: "3.7"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8081:8081
    depends_on:
      - db
  db:
    image: mongo:4.4.5
    container_name: db
    environment:
      MONGO_INITDB_DATABASE: database
