{{- $appName := .Chart.Name }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "{{ $appName }}-redis-svc:6379"
    - name: redisPassword
      value: ""