{{- $appName := .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-tinyurl
  labels:
    name: {{ $appName }}-tinyurl-svc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ $appName }}-tinyurl-svc
  template:
    metadata:
      labels:
        name: {{ $appName }}-tinyurl-svc
      annotations:
        {{- if .Values.dapr.enabled }}
        dapr.io/enabled: {{ .Values.dapr.enabled | quote }}
        dapr.io/app-id: "{{ $appName }}-tinyurl-svc"
        dapr.io/app-port: "{{ .Values.service.port }}"
        dapr.io/sidecar-liveness-probe-delay-seconds: {{ .Values.dapr.sidecar.livenessProbeDelay | quote }}
        dapr.io/sidecar-liveness-probe-timeout-seconds: {{ .Values.dapr.sidecar.livenessProbeTimeout | quote }}
        {{- end }}
        {{- if .Values.linkerd.enabled }}
        linkerd.io/inject: "enabled"
        {{- end }}
    spec:
      containers:
        - name: {{ $appName }}-tinyurl
          image: "{{ .Values.image.tinyurl.repository }}:{{ .Values.image.tinyurl.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3