{{- $appName := .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-tinyurl
  labels:
    name: {{ $appName }}-tinyurl-svc
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ $appName }}-tinyurl-svc
  template:
    metadata:
      labels:
        name: {{ $appName }}-tinyurl-svc
      annotations:
        {{- if .Values.dapr.enabled }}
        dapr.io/enabled: {{ .Values.dapr.enabled | quote }}
        dapr.io/app-id: "{{ $appName }}-tinyurl-svc"
        dapr.io/app-port: {{ .Values.dapr.incomingDaprPort | quote }}
        dapr.io/app-protocol: {{ .Values.dapr.daprProtocol | quote }}
        dapr.io/sidecar-liveness-probe-delay-seconds: {{ .Values.dapr.sidecar.livenessProbeDelay | quote }}
        dapr.io/sidecar-liveness-probe-timeout-seconds: {{ .Values.dapr.sidecar.livenessProbeTimeout | quote }}
        {{- end }}
        {{- if .Values.linkerd.enabled }}
        linkerd.io/inject: "enabled"
        {{- end }}
    spec:
      containers:
        - name: {{ $appName }}-tinyurl
          image: "{{ .Values.image.tinyurl.repository }}:{{ .Values.image.tinyurl.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $appName }}-tinyurl
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
            - containerPort: {{ .Values.dapr.incomingDaprPort }}
              protocol: TCP