{{- $appName := .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-test
  labels:
    name: {{ $appName }}-test-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ $appName }}-test-svc
  template:
    metadata:
      labels:
        name: {{ $appName }}-test-svc
      annotations:
        {{- if .Values.dapr.enabled }}
        dapr.io/enabled: {{ .Values.dapr.enabled | quote }}
        dapr.io/app-id: "{{ $appName }}-test-svc"
        dapr.io/sidecar-liveness-probe-delay-seconds: {{ .Values.dapr.sidecar.livenessProbeDelay | quote }}
        dapr.io/sidecar-liveness-probe-timeout-seconds: {{ .Values.dapr.sidecar.livenessProbeTimeout | quote }}
        {{- end }}
        {{- if .Values.linkerd.enabled }}
        linkerd.io/inject: "enabled"
        {{- end }}
    spec:
      containers:
        - name: {{ $appName }}-test
          image: "{{ .Values.image.test.repository }}:{{ .Values.image.test.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $appName }}-test
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
