{{- if .Values.ingress.enabled -}}
{{- $appName := .Chart.Name }}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $appName }}-tinyurl
  labels:
    name: {{ $appName }}-tinyurl-svc
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $appName }}-tinyurl-svc
                port:
                  number: {{ $svcPort }}
  {{- end }}
