{{- if .Values.ingress.enabled -}}
{{- $appName := .Chart.Name }}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $appName }}-tinyurl
  labels:
    name: {{ $appName }}-tinyurl-svc
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - backend:
            serviceName: {{ $appName }}-tinyurl-svc
            servicePort: {{ $svcPort }}
  {{- end }}
